### ISSUE TITLE
ECB exchange data

### ISSUE THREAD

**Issue by baarkerlounger** [ideveCore/currency-converter#10]
It would be nice to be able to configure the data source for the exchange rates. In particular it would be great to be able to use the European Central Bank's data feed rather than Google's:

https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

**Comment by ideveCore** [comment]
Hello, these modifications have already been made. Please wait for the release of the version; it might take a little longer.
