### ISSUE TITLE
Value 'Abreviation' to 'Abreviation'

### ISSUE THREAD

**Issue by alfonsocv12** [ideveCore/currency-converter#11]
Hello, do you think this is something possible?

instead of searching 

```
USD > MXN 100
```

We could use

```
1 usd to mxn
```

I think this is more natural and more people will find it useful

**Comment by ideveCore** [comment]
Thank you for the suggestion.

**Comment by ideveCore** [comment]
Hello, these modifications have already been made. Please wait for the release of the version; it might take a little longer.
