### ISSUE TITLE
Improve UI layout

### ISSUE THREAD

**Issue by bragefuglseth** [ideveCore/currency-converter#12]
The current layout of the app, for reference:

![Skjermbilde fra 2023-12-08 23-40-51](https://github.com/ideveCore/currency-converter/assets/91388039/1ea581ee-2da5-449d-9aac-0c37097fe618)

It has some issues: Different elements that are actually related to each other (like output currency and the output value) aren't visually grouped, and a button press is required to make the conversion. Here's a suggestion for improving it:

![currency-converter](https://github.com/ideveCore/currency-converter/assets/91388039/6c1d1cac-d353-4533-a070-cb306d14c7f3)

The lightbulb icon would do the same thing as the current "disclaimer" link. The results would be updated live, and not just when the convert button is pressed.

I would have addressed the UI when beginning your Circle review, but decided to suggest this beforehand so we don't have to spend so much time on design details in the actual review process.

**Comment by ideveCore** [comment]
Hello thanks for the tip
