### ISSUE TITLE
Removing in-app theme selector

### ISSUE THREAD

**Issue by bragefuglseth** [ideveCore/currency-converter#26]
From the [UI styling guidelines](https://developer.gnome.org/hig/guidelines/ui-styling.html):

> Per-app style preferences are primarily useful for text editing apps, or apps which users use for long periods of time. In these cases, the style preference can be useful as a way of controlling visual contrast and brightness.

Apps that don't fit this description generally shouldn't have an in-app theme switcher, but just follow the system setting instead.

**Comment by ideveCore** [comment]
Hello, I've already made this change
