### ISSUE TITLE
Search using abbreviation

### ISSUE THREAD

**Issue by pentrail** [ideveCore/currency-converter#4]
When searching for currencies, it would be nice to be able to search using just the abbreviation.
* Ex: instead of being forced to type "United Sta..." one could just type "USD" instead.

**Comment by ideveCore** [comment]
Hello friend, thank you for the tip, I will be working on it, in the next version we will see these changes.

**Comment by ideveCore** [comment]
Hello friend thanks for the tips, they have already been added in the update stay tuned to your distro's app store.

**Comment by ideveCore** [comment]
I'm close this issue.
